import argparse
import contextlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass
from multiprocessing import Pool
from multiprocessing.pool import AsyncResult
from pathlib import Path
from typing import Any, Final
from loguru import logger

HTML_SUFFIXES = frozenset({".html", ".htm"})
POOL_SIZE = 8
_INLINE_TAGS = "span|a|strong|em|b|i|code|label"
_DOCTYPE_RE_1 = re.compile(r"<!(doctype)(html)", re.IGNORECASE)
_DOCTYPE_RE_2 = re.compile(r"<!(DOCTYPE)(HTML)")
_INLINE_BOUNDARY_RE = re.compile(rf"(</(?:{_INLINE_TAGS})>)(<(?:{_INLINE_TAGS}))")


@dataclass
class MinifyStats:
    error = ""

    @property
    def ratio(self):
        if self.original_size == 0:
            return 0.0
        return (1 - self.minified_size / self.original_size) * 100

    @property
    def saved(self):
        return self.original_size - self.minified_size


class HTMLMinifier:
    DEFAULT_CONFIG = {
        "collapseBooleanAttributes": True,
        "collapseInlineTagWhitespace": True,
        "collapseWhitespace": True,
        "conservativeCollapse": False,
        "decodeEntities": True,
        "html5": True,
        "includeAutoGeneratedTags": False,
        "keepClosingSlash": False,
        "minifyCSS": True,
        "minifyJS": True,
        "minifyURLs": True,
        "preserveLineBreaks": False,
        "preventAttributesEscaping": False,
        "processConditionalComments": True,
        "processScripts": ["text/html"],
        "quoteCharacter": '"',
        "removeComments": True,
        "removeEmptyAttributes": True,
        "removeEmptyElements": True,
        "removeRedundantAttributes": True,
        "removeScriptTypeAttributes": True,
        "removeStyleLinkTypeAttributes": True,
        "removeTagWhitespace": True,
        "sortAttributes": True,
        "sortClassName": True,
        "trimCustomFragments": True,
        "useShortDoctype": True,
    }

    def __init__(self):
        self.config = dict(self.DEFAULT_CONFIG)
        self._check_dependencies()

    @staticmethod
    def _check_dependencies():
        if not shutil.which("html-minifier-terser"):
            logger.error("html-minifier-terser is not installed.")
            logger.warning("Install it with: npm install -g html-minifier-terser")
            sys.exit(1)

    @staticmethod
    def _fix_doctype(content):
        content = _DOCTYPE_RE_1.sub(r"<!\1 \2", content)
        content = _DOCTYPE_RE_2.sub(r"<!\1 \2", content)
        return content

    @staticmethod
    def _post_process(content):
        content = HTMLMinifier._fix_doctype(content)
        content = _INLINE_BOUNDARY_RE.sub(r"\1 \2", content)
        return content

    def _build_cli_args(self, config_file):
        return ["html-minifier-terser", "--config-file", str(config_file)]

    def minify_file(self, path):
        config_file = None
        try:
            original_size = path.stat().st_size
            with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as f:
                json.dump(self.config, f)
                config_file = Path(f.name)
            content = path.read_text(encoding="utf-8")
            cmd = self._build_cli_args(config_file)
            process = subprocess.run(
                cmd,
                input=content,
                capture_output=True,
                text=True,
                encoding="utf-8",
            )
            if process.returncode != 0:
                return MinifyStats(
                    path=path,
                    original_size=original_size,
                    minified_size=original_size,
                    success=False,
                    error=f"Minification failed: {process.stderr.strip()}",
                )
            minified_content = self._post_process(process.stdout)
            path.write_text(minified_content, encoding="utf-8")
            minified_size = path.stat().st_size
            return MinifyStats(
                path=path,
                original_size=original_size,
                minified_size=minified_size,
                success=True,
            )
        except Exception as exc:
            return MinifyStats(
                path=path,
                original_size=0,
                minified_size=0,
                success=False,
                error=str(exc),
            )
        finally:
            if config_file is not None and config_file.exists():
                with contextlib.suppress(Exception):
                    config_file.unlink()

    @staticmethod
    def find_html_files(paths):
        html_files = []
        for path in paths:
            if not path.exists():
                logger.warning(f"Path '{path}' does not exist. Skipping.")
                continue
            if path.is_file():
                if path.suffix.lower() in HTML_SUFFIXES:
                    html_files.append(path)
                else:
                    logger.warning(f"'{path}' is not an HTML file. Skipping.")
            elif path.is_dir():
                for suffix in HTML_SUFFIXES:
                    html_files.extend(path.rglob(f"*{suffix}"))
            else:
                logger.warning(f"'{path}' is neither a file nor a directory. Skipping.")
        return sorted(set(html_files))

    def minify_paths(self, paths):
        html_files = self.find_html_files(paths)
        if not html_files:
            logger.warning("No HTML files found to minify.")
            return
        total_files = len(html_files)
        print(f"Found {total_files} HTML file(s) to minify")
        print("=" * 40)
        successful = 0
        failed = 0
        total_original = 0
        total_minified = 0
        results = []
        with Pool(processes=POOL_SIZE) as pool:
            async_results = [pool.apply_async(self.minify_file, (path,)) for path in html_files]
            for async_result in async_results:
                try:
                    stats = async_result.get()
                except Exception as exc:
                    stats = MinifyStats(
                        path=Path("<unknown>"),
                        original_size=0,
                        minified_size=0,
                        success=False,
                        error=str(exc),
                    )
                results.append(stats)
                if stats.success:
                    successful += 1
                    total_original += stats.original_size
                    total_minified += stats.minified_size
                    self._print_file_stats(stats)
                else:
                    failed += 1
                    self._print_error(stats)
        self._print_summary(total_files, successful, failed, total_original, total_minified)

    def minify_directory(self, directories):
        self.minify_paths(directories)

    @staticmethod
    def _relative_display(path):
        try:
            return path.relative_to(Path.cwd())
        except ValueError:
            return path

    @staticmethod
    def _ratio_color(ratio):
        if ratio > 30:
            return "green"
        if ratio > 10:
            return "yellow"
        return "red"

    def _print_file_stats(self, stats):
        rel_path = self._relative_display(stats.path)
        original_kb = stats.original_size / 1024
        minified_kb = stats.minified_size / 1024
        saved_kb = stats.saved / 1024
        color = self._ratio_color(stats.ratio)
        logger.opt(colors=True).info(
            f"<green>✓</green> <white>{rel_path}</white>\n"
            f"  <blue>Original: {original_kb:.2f} KB</blue>  "
            f"<{color}>→ {minified_kb:.2f} KB</{color}>  "
            f"<magenta>(-{saved_kb:.2f} KB, "
            f"<{color}>{stats.ratio:.1f}%</{color}>)</magenta>"
        )

    def _print_error(self, stats):
        rel_path = self._relative_display(stats.path)
        logger.opt(colors=True).error(f"<red>✗ {rel_path}</red>\n  <red>Error: {stats.error}</red>")

    def _print_summary(
        self,
        total,
        successful,
        failed,
        total_original,
        total_minified,
    ):
        total_saved = total_original - total_minified
        overall_ratio = (total_saved / total_original * 100) if total_original > 0 else 0.0
        original_mb = total_original / (1024 * 1024)
        minified_mb = total_minified / (1024 * 1024)
        saved_mb = total_saved / (1024 * 1024)
        print("=" * 40)
        print("Summary")
        print("=" * 40)
        logger.opt(colors=True).info(f"<white>Files processed:  {total}</white>")
        logger.opt(colors=True).info(f"<green>✓ Successful:     {successful}</green>")
        if failed > 0:
            logger.opt(colors=True).info(f"<red>✗ Failed:         {failed}</red>")
        logger.opt(colors=True).info(f"<white>Original size:    {original_mb:.2f} MB</white>")
        logger.opt(colors=True).info(f"<white>Minified size:    {minified_mb:.2f} MB</white>")
        logger.opt(colors=True).info(f"<green>Total saved:      {saved_mb:.2f} MB ({overall_ratio:.1f}%)</green>")
        print("=" * 40)


def _configure_logger(no_color):
    logger.remove()
    if no_color:
        logger.add(
            sys.stderr,
            colorize=False,
            format="{message}",
        )
    else:
        logger.add(
            sys.stderr,
            colorize=True,
            format="<level>{message}</level>",
        )


def main():
    parser = argparse.ArgumentParser(
        description="Minify HTML files recursively using html-minifier-terser",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s
  %(prog)s file1.html file2.html
  %(prog)s public/ dist/
  %(prog)s index.html src/
        """,
    )
    parser.add_argument(
        "paths",
        nargs="*",
        default=["."],
        help="Files or directories to process (default: current directory)",
    )
    parser.add_argument("--no-color", action="store_true", help="Disable colored output")
    args = parser.parse_args()
    _configure_logger(bool(args.no_color))
    raw_paths = list(args.paths)
    paths = [Path(p).resolve() for p in raw_paths]
    minifier = HTMLMinifier()
    minifier.minify_paths(paths)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
